AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: SAM Template for Mercury

Parameters:
  ApiTestToken:
    Type: String
    Description: 'Iex test token'
  ApiToken:
    Type: String
    Description: 'Iex prod token'
  AwsTableName:
    Type: String
    Default: 'IexSnapshot'
    Description: 'Name of DynamoDB table to store Symbol data'
  AwsTableRegion:
    Type: String
    Default: 'us-east-1'
    Description: 'DynamoDB table region'
  LoggerType:
      Type: String
      Default: 'json'
      Description: 'Logs format. If value = json logs in json format will be generated, otherwise - standard text logs'
  TestEnvironmentFlag:
    Type: String
    Default: 'True'
    Description: 'Test environment flag'

Resources:
# ROLE
  MercuryLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub mercury-lambda-execution-role
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
# END ROLE

# LAMBDA
  MercuryLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: !Sub 'mercury-lambda'
      Runtime: python3.7
      CodeUri: lambdas/mercury/
      Role: !GetAtt MercuryLambdaExecutionRole.Arn
      MemorySize: 128
      Timeout: 30
      AutoPublishAlias: "live"
      Handler: handler.lambda_handler
      Description: Mercury Lambda
      DeploymentPreference:
        Type: AllAtOnce
      Environment:
        Variables:
          API_TEST_TOKEN: !Ref ApiTestToken
          API_TOKEN: !Ref ApiToken
          AWS_TABLE_NAME: !Ref AwsTableName
          AWS_TABLE_REGION: !Ref AwsTableRegion
          LOGGER_TYPE: !Ref LoggerType
          TEST_ENVIRONMENT: !Ref TestEnvironmentFlag
      Events:
        EveryWorkDayAt5:
          Type: Schedule
          Properties:
            Schedule: 'cron(0 5 ? * MON-FRI *)'
# END LAMBDA

Outputs:
  MercuryLambdaExecutionRole:
    Description: "Mercury Lambda Execution Role Arn"
    Value: !GetAtt MercuryLambdaExecutionRole.Arn
  MercuryLambda:
    Description: "Mercury Lambda Function"
    Value: !GetAtt MercuryLambda.Arn
  MercuryLambdaVersion:
    Description: "Mercury Lambda Version"
    Value: !GetAtt MercuryLambda.Version